version: '3'
services:
  # MySQL container
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 102030
      MYSQL_DATABASE: library
      MYSQL_USER: libprod
      MYSQL_PASSWORD: 102030
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Spring Boot application container
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/library?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: libprod
      SPRING_DATASOURCE_PASSWORD: 102030
      SPRING_PROFILES_ACTIVE: dev

volumes:
  db_data:
